service: serverless-bentobot

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  deploymentBucket:
    blockPublicAccess: true

functions:
  bentobot:
    handler: bentobot
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
      RUN_AT_TIME: 11:15
      TARGET_TIMEZONE: Europe/Stockholm
    events:
      - schedule: cron(15 * ? * MON-FRI *)
